# Generated by Django 3.1.3 on 2020-11-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='uploaded'),
        ),
    ]
